import React, { useRef, useEffect } from "react";
import { a } from "@react-spring/three";
import { useAnimations, useGLTF } from "@react-three/drei";

import beedrillScene from "../../assets/3d/beedrill.glb";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: fanaya2001 (https://sketchfab.com/fanaya2001)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/beedrill-d1bdf5065da3415cbbce5f91406bdd70
Title: Beedrill
*/

const Beedrill = (props) => {
  const beedrillRef = useRef();
  const { nodes, materials, animations } = useGLTF(beedrillScene);
  const { actions } = useAnimations(animations, beedrillRef);
  console.log(animations);

  useEffect(() => {
    if (actions && actions["Take 001"]) {
      actions["Take 001"].play();
    }
  }, [actions]);
  return (
    <>
      <a.group ref={beedrillRef} {...props} dispose={null}>
        <a.group name="Sketchfab_Scene">
          <a.group
            name="Sketchfab_model"
            rotation={[-Math.PI / 2, 0, 1]}
            position={[-170, 100, -350]}
          >
            <a.group
              name="a38f5c29add2417493488369049ea470fbx"
              rotation={[Math.PI / 2, 0, 0]}
            >
              <a.group name="Object_2">
                <a.group name="RootNode">
                  <a.group
                    name="Beedrill_Low"
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <a.group
                    name="base"
                    position={[0, 62.64, -12.009]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  >
                    <a.group name="Object_6">
                      <primitive object={nodes._rootJoint} />
                      <skinnedMesh
                        name="Object_9"
                        geometry={nodes.Object_9.geometry}
                        material={materials.Beedrill}
                        skeleton={nodes.Object_9.skeleton}
                      />
                      <skinnedMesh
                        name="Object_51"
                        geometry={nodes.Object_51.geometry}
                        material={materials.Cell}
                        skeleton={nodes.Object_51.skeleton}
                      />
                      <a.group
                        name="Object_8"
                        rotation={[-Math.PI / 2, 0, 0]}
                      />
                      <a.group
                        name="Object_50"
                        rotation={[-Math.PI / 2, 0, 0]}
                      />
                    </a.group>
                  </a.group>
                  <a.group
                    name="PhysCamera001"
                    position={[332.245, 186.136, 96.471]}
                    rotation={[-0.418, 0.569, 0.235]}
                  />
                  <a.group
                    name="PhysCamera001Target"
                    position={[237.113, 125.769, -39.39]}
                    rotation={[-0.418, 0.569, 0.235]}
                  />
                  <a.group
                    name="Beedrill_Low001"
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                </a.group>
              </a.group>
            </a.group>
          </a.group>
        </a.group>
      </a.group>
    </>
  );
};

export default Beedrill;
