import React, { useRef, useEffect } from "react";
import { a } from "@react-spring/three";
import { useAnimations, useGLTF } from "@react-three/drei";

import boppin from "../../assets/3d/boppin.glb";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: zcythe (https://sketchfab.com/zcythe)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/boppin-ariados-d3d9fed0764743a8a4c7b884f801812d
Title: Boppin' Ariados
*/

const Boppin = (props) => {
  const boppinRef = useRef();
  const {
    nodes: boppinNodes,
    materials: boppinMaterials,
    animations: boppinAnimations,
  } = useGLTF(boppin);
  const { actions: boppinActions } = useAnimations(boppinAnimations, boppinRef);

  useEffect(() => {
    if (boppinActions && boppinActions["boppin"]) {
      boppinActions["boppin"].play();
    }
  }, [boppinActions]);

  return (
    <>
      <a.group ref={boppinRef} {...props} dispose={null}>
        <a.group name="Sketchfab_Scene">
          <a.group
            name="Sketchfab_model"
            rotation={[-Math.PI / 2, -0.8, 2]}
            position={[-350, 100, 0]}
            scale={8.975}
          >
            <a.group
              name="dbdca8658ad34f5f91de7f46d3590cd1fbx"
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.7}
            >
              <a.group name="Object_2">
                <a.group name="RootNode">
                  <a.group name="Ariados">
                    <a.group name="Rig" scale={[1.011, 1.027, 1.011]}>
                      <a.group name="Object_6">
                        <primitive object={boppinNodes._rootJoint} />
                        <skinnedMesh
                          name="Object_35"
                          geometry={boppinNodes.Object_35.geometry}
                          material={boppinMaterials.Limbs}
                          skeleton={boppinNodes.Object_35.skeleton}
                        />
                        <skinnedMesh
                          name="Object_36"
                          geometry={boppinNodes.Object_36.geometry}
                          material={boppinMaterials.Horns}
                          skeleton={boppinNodes.Object_36.skeleton}
                        />
                        <skinnedMesh
                          name="Object_37"
                          geometry={boppinNodes.Object_37.geometry}
                          material={boppinMaterials.pupil}
                          skeleton={boppinNodes.Object_37.skeleton}
                        />
                        <skinnedMesh
                          name="Object_38"
                          geometry={boppinNodes.Object_38.geometry}
                          material={boppinMaterials.MAT_Main}
                          skeleton={boppinNodes.Object_38.skeleton}
                        />
                        <skinnedMesh
                          name="Object_39"
                          geometry={boppinNodes.Object_39.geometry}
                          material={boppinMaterials.Refl}
                          skeleton={boppinNodes.Object_39.skeleton}
                        />
                        <skinnedMesh
                          name="Object_40"
                          geometry={boppinNodes.Object_40.geometry}
                          material={boppinMaterials.Sclera}
                          skeleton={boppinNodes.Object_40.skeleton}
                        />
                        <a.group name="Object_34" />
                      </a.group>
                    </a.group>
                  </a.group>
                  <a.group name="Ariados1" />
                </a.group>
              </a.group>
            </a.group>
          </a.group>
        </a.group>
      </a.group>
    </>
  );
};

export default Boppin;
