import React, { useEffect, useRef } from "react";
import { a } from "@react-spring/three";
import { useAnimations, useGLTF } from "@react-three/drei";

import selfScene from "../../assets/3d/contact.glb";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Hadrien59 (https://sketchfab.com/Hadrien59)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-playground-59fc99d8dcb146f3a6c16dbbcc4680da
Title: Robot Playground
*/

const ContactCharacter = (props) => {
  const contactRef = useRef();
  const { nodes, materials, animations } = useGLTF(selfScene);

  const { actions } = useAnimations(animations, contactRef);

  useEffect(() => {
    if (actions && actions["Experiment"]) {
      actions["Experiment"].play();
    }
  }, [actions]);

  return (
    <>
      <a.group ref={contactRef} {...props} dispose={null}>
        <a.group name="Sketchfab_Scene" scale={2.4}>
          <a.group
            name="Sketchfab_model"
            rotation={[-Math.PI / 2, 0, 0]}
            position={[40, 10, 160]}
          >
            <a.group
              name="000846fff9e546569ee038af7e24655afbx"
              rotation={[Math.PI / 2, 0, 0]}
            >
              <a.group name="Object_2">
                <a.group name="RootNode">
                  <a.group name="holo" scale={1.87653852}>
                    <a.group name="ground" position={[0, 0.39011046, 0]}>
                      <a.group
                        name="pDisc1"
                        position={[0, -0.38833466, 0]}
                        scale={11.11418629}
                      >
                        <mesh
                          name="pDisc1_holo1_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.pDisc1_holo1_0.geometry}
                          material={materials.holo1}
                        />
                      </a.group>
                      <a.group
                        name="pPipe4"
                        position={[0, -0.42896184, 0]}
                        rotation={[0, -0.31062191, 0]}
                      >
                        <mesh
                          name="pPipe4_holo1_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.pPipe4_holo1_0.geometry}
                          material={materials.holo1}
                        />
                        <a.group
                          name="MASH1_ReproMesh2"
                          position={[0, 0.42896184, 0]}
                        >
                          <mesh
                            name="MASH1_ReproMesh2_holo1_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.MASH1_ReproMesh2_holo1_0.geometry}
                            material={materials.holo1}
                          />
                        </a.group>
                      </a.group>
                      <a.group
                        name="pPipe2"
                        position={[0, -0.57622349, 0]}
                        rotation={[0, 0.31062191, 0]}
                      >
                        <mesh
                          name="pPipe2_holo1_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.pPipe2_holo1_0.geometry}
                          material={materials.holo1}
                        />
                        <a.group
                          name="MASH1_ReproMesh3"
                          position={[0, 0.57622349, 0]}
                          scale={[0.81861287, 0.80425197, 0.81861287]}
                        >
                          <mesh
                            name="MASH1_ReproMesh3_holo1_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.MASH1_ReproMesh3_holo1_0.geometry}
                            material={materials.holo1}
                          />
                        </a.group>
                        <a.group
                          name="pPipe3"
                          rotation={[0, 0.68363297, 0]}
                          scale={0.85587132}
                        >
                          <mesh
                            name="pPipe3_holo1_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.pPipe3_holo1_0.geometry}
                            material={materials.holo1}
                          />
                        </a.group>
                      </a.group>
                      <a.group name="pPipe1" rotation={[0, -0.31062191, 0]}>
                        <mesh
                          name="pPipe1_holo1_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.pPipe1_holo1_0.geometry}
                          material={materials.holo1}
                        />
                        <a.group
                          name="MASH1_ReproMesh1"
                          scale={[1.03316176, 1, 1.03316176]}
                        >
                          <mesh
                            name="MASH1_ReproMesh1_holo1_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.MASH1_ReproMesh1_holo1_0.geometry}
                            material={materials.holo1}
                          />
                        </a.group>
                      </a.group>
                    </a.group>
                    <a.group
                      name="group36"
                      position={[0.33016691, 0, -0.09905007]}
                      rotation={[-Math.PI, -0.14214182, -Math.PI]}
                      scale={0.9894923}
                    >
                      <a.group name="group39" rotation={[0, 0.8771504, 0]}>
                        <a.group
                          name="group37"
                          position={[-4.62958527, 14.29357243, 1.99375391]}
                        >
                          <a.group
                            name="group31"
                            position={[4.62958527, -4.88695621, -1.99375391]}
                            rotation={[0.00605194, 0.00006045, 0.00998781]}
                            scale={1.18244982}
                          >
                            <a.group
                              name="group35"
                              position={[0.22452737, 0.10743211, 0.00330562]}
                              rotation={[-Math.PI, -1.4628533, Math.PI]}
                            >
                              <a.group
                                name="group38"
                                position={[0.03934956, 0.75493205, 0.24770626]}
                              >
                                <a.group
                                  name="group29"
                                  position={[
                                    -0.02719754, -10.24469852, -0.03557609,
                                  ]}
                                  rotation={[0, Math.PI / 4, 0]}
                                >
                                  <a.group
                                    name="group21"
                                    position={[-12.68695641, 10.69662666, 0]}
                                    scale={0.24485487}
                                  >
                                    <a.group
                                      name="MASH1_ReproMesh12"
                                      position={[0, 0.23902394, 0]}
                                      rotation={[-1.13186462, 0, Math.PI / 2]}
                                      scale={[1.03316176, 1, 1.03316176]}
                                    >
                                      <mesh
                                        name="MASH1_ReproMesh12_holo1_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                          nodes.MASH1_ReproMesh12_holo1_0
                                            .geometry
                                        }
                                        material={materials.holo1}
                                      />
                                    </a.group>
                                    <a.group
                                      name="group14"
                                      rotation={[0, 1.13186456, 0]}
                                    >
                                      <a.group
                                        name="group30"
                                        rotation={[0.49203666, 0, 0]}
                                        scale={3.16948128}
                                      >
                                        <a.group
                                          name="pSuperShape2"
                                          scale={2.0762043}
                                        >
                                          <mesh
                                            name="pSuperShape2_holo1_0"
                                            castShadow
                                            receiveShadow
                                            geometry={
                                              nodes.pSuperShape2_holo1_0
                                                .geometry
                                            }
                                            material={materials.holo1}
                                          />
                                        </a.group>
                                        <a.group
                                          name="pSuperShape3"
                                          scale={2.0762043}
                                        >
                                          <mesh
                                            name="pSuperShape3_holo1_0"
                                            castShadow
                                            receiveShadow
                                            geometry={
                                              nodes.pSuperShape3_holo1_0
                                                .geometry
                                            }
                                            material={materials.holo1}
                                          />
                                        </a.group>
                                      </a.group>
                                    </a.group>
                                  </a.group>
                                </a.group>
                                <a.group
                                  name="group28"
                                  position={[
                                    -0.02719754, -10.24469852, -0.03557609,
                                  ]}
                                  rotation={[0, Math.PI / 2, 0]}
                                >
                                  <a.group
                                    name="group21_1"
                                    position={[-12.68695641, 10.69662666, 0]}
                                    scale={0.24469887}
                                  >
                                    <a.group
                                      name="MASH1_ReproMesh12_1"
                                      position={[0, 0.23902394, 0]}
                                      rotation={[-1.13186462, 0, Math.PI / 2]}
                                      scale={[1.03316176, 1, 1.03316176]}
                                    >
                                      <a.group name="MASH1_ReproMesh19">
                                        <mesh
                                          name="MASH1_ReproMesh19_holo1_0"
                                          castShadow
                                          receiveShadow
                                          geometry={
                                            nodes.MASH1_ReproMesh19_holo1_0
                                              .geometry
                                          }
                                          material={materials.holo1}
                                        />
                                      </a.group>
                                    </a.group>
                                    <a.group
                                      name="group14_1"
                                      rotation={[0, 1.13186456, 0]}
                                    >
                                      <a.group
                                        name="group7"
                                        rotation={[
                                          0.31736696, -0.65883326, 1.52087191,
                                        ]}
                                        scale={2.04826188}
                                      >
                                        <a.group name="pGear1">
                                          <mesh
                                            name="pGear1_holo1_0"
                                            castShadow
                                            receiveShadow
                                            geometry={
                                              nodes.pGear1_holo1_0.geometry
                                            }
                                            material={materials.holo1}
                                          />
                                        </a.group>
                                        <a.group name="pGear2">
                                          <mesh
                                            name="pGear2_holo1_0"
                                            castShadow
                                            receiveShadow
                                            geometry={
                                              nodes.pGear2_holo1_0.geometry
                                            }
                                            material={materials.holo1}
                                          />
                                        </a.group>
                                      </a.group>
                                    </a.group>
                                  </a.group>
                                </a.group>
                                <a.group
                                  name="group27"
                                  position={[
                                    -0.02719754, -10.24469852, -0.03557609,
                                  ]}
                                  rotation={[-Math.PI, Math.PI / 4, Math.PI]}
                                >
                                  <a.group
                                    name="group20"
                                    position={[-12.68695641, 10.69662666, 0]}
                                    scale={0.24469887}
                                  >
                                    <a.group
                                      name="MASH1_ReproMesh11"
                                      position={[0, 0.23902394, 0]}
                                      rotation={[-1.13186462, 0, Math.PI / 2]}
                                      scale={[1.03316176, 1, 1.03316176]}
                                    >
                                      <a.group name="MASH1_ReproMesh18">
                                        <mesh
                                          name="MASH1_ReproMesh18_holo1_0"
                                          castShadow
                                          receiveShadow
                                          geometry={
                                            nodes.MASH1_ReproMesh18_holo1_0
                                              .geometry
                                          }
                                          material={materials.holo1}
                                        />
                                      </a.group>
                                    </a.group>
                                    <a.group
                                      name="group13"
                                      rotation={[0, 1.13186456, 0]}
                                    >
                                      <a.group
                                        name="group6"
                                        position={[0, 0.02839997, 0]}
                                        rotation={[
                                          0.47916902, 0.09980535, -0.00225946,
                                        ]}
                                        scale={2.37046385}
                                      >
                                        <a.group name="pHelix1">
                                          <mesh
                                            name="pHelix1_holo1_0"
                                            castShadow
                                            receiveShadow
                                            geometry={
                                              nodes.pHelix1_holo1_0.geometry
                                            }
                                            material={materials.holo1}
                                          />
                                        </a.group>
                                        <a.group name="pHelix2">
                                          <mesh
                                            name="pHelix2_holo1_0"
                                            castShadow
                                            receiveShadow
                                            geometry={
                                              nodes.pHelix2_holo1_0.geometry
                                            }
                                            material={materials.holo1}
                                          />
                                        </a.group>
                                      </a.group>
                                    </a.group>
                                  </a.group>
                                </a.group>
                                <a.group
                                  name="group26"
                                  position={[
                                    -0.02719754, -10.24469852, -0.03557609,
                                  ]}
                                  rotation={[-Math.PI, 0, -Math.PI]}
                                >
                                  <a.group
                                    name="group19"
                                    position={[-12.68695641, 10.69662666, 0]}
                                    scale={0.24469887}
                                  >
                                    <a.group
                                      name="MASH1_ReproMesh10"
                                      position={[0, 0.23902394, 0]}
                                      rotation={[-1.13186462, 0, Math.PI / 2]}
                                      scale={[1.03316176, 1, 1.03316176]}
                                    >
                                      <a.group name="MASH1_ReproMesh17">
                                        <mesh
                                          name="MASH1_ReproMesh17_holo1_0"
                                          castShadow
                                          receiveShadow
                                          geometry={
                                            nodes.MASH1_ReproMesh17_holo1_0
                                              .geometry
                                          }
                                          material={materials.holo1}
                                        />
                                      </a.group>
                                    </a.group>
                                    <a.group
                                      name="group12"
                                      rotation={[0, 1.13186456, 0]}
                                    >
                                      <a.group
                                        name="group4"
                                        position={[
                                          -0.2535269, 1.10321629, -0.40172559,
                                        ]}
                                        rotation={[
                                          -0.1764001, -0.67250076, 0.27320637,
                                        ]}
                                        scale={1.55426598}
                                      >
                                        <a.group
                                          name="pPyramid1"
                                          scale={[
                                            5.26279593, 7.63659906, 5.26279593,
                                          ]}
                                        >
                                          <mesh
                                            name="pPyramid1_holo1_0"
                                            castShadow
                                            receiveShadow
                                            geometry={
                                              nodes.pPyramid1_holo1_0.geometry
                                            }
                                            material={materials.holo1}
                                          />
                                        </a.group>
                                        <a.group
                                          name="pPyramid2"
                                          scale={[
                                            5.5720644, 8.08536339, 5.5720644,
                                          ]}
                                        >
                                          <mesh
                                            name="pPyramid2_holo1_0"
                                            castShadow
                                            receiveShadow
                                            geometry={
                                              nodes.pPyramid2_holo1_0.geometry
                                            }
                                            material={materials.holo1}
                                          />
                                        </a.group>
                                      </a.group>
                                    </a.group>
                                  </a.group>
                                </a.group>
                                <a.group
                                  name="group25"
                                  position={[
                                    -0.02719754, -10.24469852, -0.03557609,
                                  ]}
                                  rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}
                                >
                                  <a.group
                                    name="group18"
                                    position={[-12.69165039, 10.69662666, 0]}
                                    scale={0.24465945}
                                  >
                                    <a.group
                                      name="MASH1_ReproMesh9"
                                      position={[0, 0.23902394, 0]}
                                      rotation={[-1.13186462, 0, Math.PI / 2]}
                                      scale={[1.03316176, 1, 1.03316176]}
                                    >
                                      <a.group name="MASH1_ReproMesh16">
                                        <mesh
                                          name="MASH1_ReproMesh16_holo1_0"
                                          castShadow
                                          receiveShadow
                                          geometry={
                                            nodes.MASH1_ReproMesh16_holo1_0
                                              .geometry
                                          }
                                          material={materials.holo1}
                                        />
                                      </a.group>
                                    </a.group>
                                    <a.group
                                      name="group11"
                                      rotation={[0, 1.13186456, 0]}
                                    >
                                      <a.group
                                        name="group5"
                                        rotation={[
                                          0.2221404, 0.15993673, 0.92791959,
                                        ]}
                                        scale={1.88956094}
                                      >
                                        <a.group name="pTorus2">
                                          <mesh
                                            name="pTorus2_holo1_0"
                                            castShadow
                                            receiveShadow
                                            geometry={
                                              nodes.pTorus2_holo1_0.geometry
                                            }
                                            material={materials.holo1}
                                          />
                                        </a.group>
                                        <a.group name="pTorus1">
                                          <mesh
                                            name="pTorus1_holo1_0"
                                            castShadow
                                            receiveShadow
                                            geometry={
                                              nodes.pTorus1_holo1_0.geometry
                                            }
                                            material={materials.holo1}
                                          />
                                        </a.group>
                                      </a.group>
                                    </a.group>
                                  </a.group>
                                </a.group>
                                <a.group
                                  name="group23"
                                  position={[
                                    -0.02719754, -10.24469852, -0.03557609,
                                  ]}
                                  rotation={[0, -Math.PI / 4, 0]}
                                >
                                  <a.group
                                    name="group16"
                                    position={[-12.68695641, 10.69662666, 0]}
                                    scale={0.24469887}
                                  >
                                    <a.group
                                      name="MASH1_ReproMesh7"
                                      position={[0, 0.23902394, 0]}
                                      rotation={[-1.13186462, 0, Math.PI / 2]}
                                      scale={[1.03316176, 1, 1.03316176]}
                                    >
                                      <a.group name="MASH1_ReproMesh14">
                                        <mesh
                                          name="MASH1_ReproMesh14_holo1_0"
                                          castShadow
                                          receiveShadow
                                          geometry={
                                            nodes.MASH1_ReproMesh14_holo1_0
                                              .geometry
                                          }
                                          material={materials.holo1}
                                        />
                                      </a.group>
                                    </a.group>
                                    <a.group
                                      name="group9"
                                      rotation={[0, 1.13186456, 0]}
                                      scale={1.3030808}
                                    >
                                      <a.group
                                        name="group2"
                                        rotation={[
                                          -0.62322352, -0.61665682, 0.10158479,
                                        ]}
                                      >
                                        <a.group
                                          name="pCube1"
                                          scale={4.80796385}
                                        >
                                          <mesh
                                            name="pCube1_holo1_0"
                                            castShadow
                                            receiveShadow
                                            geometry={
                                              nodes.pCube1_holo1_0.geometry
                                            }
                                            material={materials.holo1}
                                          />
                                        </a.group>
                                        <a.group
                                          name="pCube2"
                                          scale={4.91844606}
                                        >
                                          <mesh
                                            name="pCube2_holo1_0"
                                            castShadow
                                            receiveShadow
                                            geometry={
                                              nodes.pCube2_holo1_0.geometry
                                            }
                                            material={materials.holo1}
                                          />
                                        </a.group>
                                      </a.group>
                                    </a.group>
                                  </a.group>
                                </a.group>
                                <a.group
                                  name="group22"
                                  position={[
                                    -0.02719754, -10.24469852, -0.03557609,
                                  ]}
                                >
                                  <a.group
                                    name="group15"
                                    position={[-12.68695641, 10.69662666, 0]}
                                    scale={0.24469887}
                                  >
                                    <a.group
                                      name="MASH1_ReproMesh6"
                                      position={[0, 0.23902394, 0]}
                                      rotation={[-1.13186462, 0, Math.PI / 2]}
                                      scale={[1.03316176, 1, 1.03316176]}
                                    >
                                      <a.group name="MASH1_ReproMesh13">
                                        <mesh
                                          name="MASH1_ReproMesh13_holo1_0"
                                          castShadow
                                          receiveShadow
                                          geometry={
                                            nodes.MASH1_ReproMesh13_holo1_0
                                              .geometry
                                          }
                                          material={materials.holo1}
                                        />
                                      </a.group>
                                    </a.group>
                                    <a.group
                                      name="group8"
                                      rotation={[0, 1.13186456, 0]}
                                    >
                                      <a.group
                                        name="group1"
                                        rotation={[-0.51253664, 0, 0]}
                                        scale={[
                                          1.2227813, 0.98027784, 1.2227813,
                                        ]}
                                      >
                                        <a.group
                                          name="pCylinder2"
                                          scale={3.56875467}
                                        >
                                          <mesh
                                            name="pCylinder2_holo1_0"
                                            castShadow
                                            receiveShadow
                                            geometry={
                                              nodes.pCylinder2_holo1_0.geometry
                                            }
                                            material={materials.holo1}
                                          />
                                        </a.group>
                                        <a.group
                                          name="pCylinder3"
                                          scale={3.66512942}
                                        >
                                          <mesh
                                            name="pCylinder3_holo1_0"
                                            castShadow
                                            receiveShadow
                                            geometry={
                                              nodes.pCylinder3_holo1_0.geometry
                                            }
                                            material={materials.holo1}
                                          />
                                        </a.group>
                                      </a.group>
                                    </a.group>
                                  </a.group>
                                </a.group>
                                <a.group
                                  name="pCylinder4"
                                  position={[
                                    -0.02719754, 0.45763803, -0.03557609,
                                  ]}
                                  scale={[0.81754488, 0.43915924, 0.81754488]}
                                >
                                  <mesh
                                    name="pCylinder4_holo1_0"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.pCylinder4_holo1_0.geometry}
                                    material={materials.holo1}
                                  />
                                </a.group>
                              </a.group>
                              <a.group
                                name="group24"
                                position={[
                                  0.02090277, -10.72345161, 0.22357671,
                                ]}
                                rotation={[0, -Math.PI / 2, 0]}
                              >
                                <a.group
                                  name="group17"
                                  position={[
                                    -12.35573578, 11.79705811, 0.23114707,
                                  ]}
                                  scale={0.29528141}
                                >
                                  <a.group
                                    name="group10"
                                    rotation={[Math.PI, -1.16271595, Math.PI]}
                                  >
                                    <a.group name="group3" scale={1.44468892}>
                                      <a.group
                                        name="pPlatonic1"
                                        scale={3.23893332}
                                      >
                                        <mesh
                                          name="pPlatonic1_holo1_0"
                                          castShadow
                                          receiveShadow
                                          geometry={
                                            nodes.pPlatonic1_holo1_0.geometry
                                          }
                                          material={materials.holo1}
                                        />
                                      </a.group>
                                      <a.group
                                        name="pPlatonic2"
                                        scale={3.41385961}
                                      >
                                        <mesh
                                          name="pPlatonic2_holo1_0"
                                          castShadow
                                          receiveShadow
                                          geometry={
                                            nodes.pPlatonic2_holo1_0.geometry
                                          }
                                          material={materials.holo1}
                                        />
                                      </a.group>
                                    </a.group>
                                  </a.group>
                                  <a.group
                                    name="MASH1_ReproMesh8"
                                    position={[
                                      0.22650225, 0.00599701, -0.549182,
                                    ]}
                                    rotation={[-1.13186462, 0, Math.PI / 2]}
                                    scale={[0.81806779, 0.79181004, 0.81806779]}
                                  >
                                    <a.group name="MASH1_ReproMesh15">
                                      <mesh
                                        name="MASH1_ReproMesh15_holo1_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                          nodes.MASH1_ReproMesh15_holo1_0
                                            .geometry
                                        }
                                        material={materials.holo1}
                                      />
                                    </a.group>
                                  </a.group>
                                </a.group>
                              </a.group>
                            </a.group>
                            <a.group
                              name="pPlatonic3"
                              position={[-0.347785, -0.12418361, -0.32427976]}
                              scale={0.001}
                            >
                              <mesh
                                name="pPlatonic3_holo1_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.pPlatonic3_holo1_0.geometry}
                                material={materials.holo1}
                              />
                            </a.group>
                          </a.group>
                        </a.group>
                      </a.group>
                    </a.group>
                  </a.group>
                  <a.group name="bot_geo">
                    <a.group name="knee" />
                    <a.group name="foot" />
                    <a.group name="hand" />
                    <a.group name="upperLeg" />
                    <a.group name="body" />
                    <a.group name="index" />
                    <a.group name="pinky" />
                    <a.group name="thumb" />
                    <a.group name="earBall" />
                    <a.group name="topHeadBall" />
                    <a.group name="topHeadTube" />
                    <a.group name="shoulder" />
                    <a.group name="midfinger" />
                    <a.group name="neckTop" />
                    <a.group name="neck" />
                    <a.group name="head" />
                    <a.group name="topHead" />
                    <a.group name="hip" />
                    <a.group name="earTube" />
                    <a.group name="ear" />
                    <a.group name="neckBase" />
                    <a.group name="face">
                      <a.group
                        name="eyeCloseKawaii"
                        position={[-13.6123209, -3.3210628, -2.90448236]}
                        scale={1.28994262}
                      />
                      <a.group
                        name="eye"
                        position={[0.41226044, -4.25687742, -1.92047405]}
                        scale={1.15518022}
                      />
                      <a.group
                        name="eyeSmile"
                        position={[-13.48230171, -3.21053624, -2.24926662]}
                        scale={1.15489829}
                      />
                      <a.group
                        name="eyeClose"
                        position={[-15.99761486, 1.37369108, -1.49772251]}
                      />
                      <a.group
                        name="happy"
                        position={[-13.38803291, -0.04739363, -1.5199194]}
                      />
                      <a.group
                        name="smile"
                        position={[0, -0.00019343, -1.5199194]}
                      />
                      <a.group
                        name="o"
                        position={[-13.38803291, 1.37413132, -1.2541256]}
                      />
                      <a.group
                        name="close"
                        position={[-13.38803291, -0.04485827, -1.5199194]}
                      />
                      <a.group
                        name="group34"
                        rotation={[-Math.PI, 0, 0]}
                        scale={-1}
                      >
                        <a.group
                          name="eyeCloseKawaii1"
                          position={[-13.6123209, -3.3210628, -2.90448236]}
                          scale={1.28994262}
                        />
                        <a.group
                          name="eye1"
                          position={[-5.67882586, -4.25687742, -1.92047405]}
                          rotation={[-Math.PI, 0, 0]}
                          scale={[-1.15499997, -1.15518022, -1.15518022]}
                        />
                        <a.group
                          name="eyeSmile1"
                          position={[-13.48230171, -3.21053624, -2.24926662]}
                          scale={1.15489829}
                        />
                        <a.group
                          name="eyeClose1"
                          position={[-15.99761486, 1.37369108, -1.49772251]}
                        />
                      </a.group>
                    </a.group>
                    <a.group name="arm2" />
                  </a.group>
                  <a.group name="Group">
                    <a.group name="Main">
                      <a.group name="DeformationSystem">
                        <a.group name="Object_159">
                          <primitive object={nodes._rootJoint} />
                          <skinnedMesh
                            name="Object_162"
                            geometry={nodes.Object_162.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_162.skeleton}
                          />
                          <skinnedMesh
                            name="Object_164"
                            geometry={nodes.Object_164.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_164.skeleton}
                          />
                          <skinnedMesh
                            name="Object_166"
                            geometry={nodes.Object_166.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_166.skeleton}
                          />
                          <skinnedMesh
                            name="Object_168"
                            geometry={nodes.Object_168.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_168.skeleton}
                          />
                          <skinnedMesh
                            name="Object_170"
                            geometry={nodes.Object_170.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_170.skeleton}
                          />
                          <skinnedMesh
                            name="Object_172"
                            geometry={nodes.Object_172.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_172.skeleton}
                          />
                          <skinnedMesh
                            name="Object_174"
                            geometry={nodes.Object_174.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_174.skeleton}
                          />
                          <skinnedMesh
                            name="Object_176"
                            geometry={nodes.Object_176.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_176.skeleton}
                          />
                          <skinnedMesh
                            name="Object_178"
                            geometry={nodes.Object_178.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_178.skeleton}
                          />
                          <skinnedMesh
                            name="Object_180"
                            geometry={nodes.Object_180.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_180.skeleton}
                          />
                          <skinnedMesh
                            name="Object_182"
                            geometry={nodes.Object_182.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_182.skeleton}
                          />
                          <skinnedMesh
                            name="Object_184"
                            geometry={nodes.Object_184.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_184.skeleton}
                          />
                          <skinnedMesh
                            name="Object_186"
                            geometry={nodes.Object_186.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_186.skeleton}
                          />
                          <skinnedMesh
                            name="Object_188"
                            geometry={nodes.Object_188.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_188.skeleton}
                          />
                          <skinnedMesh
                            name="Object_190"
                            geometry={nodes.Object_190.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_190.skeleton}
                          />
                          <skinnedMesh
                            name="Object_192"
                            geometry={nodes.Object_192.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_192.skeleton}
                          />
                          <skinnedMesh
                            name="Object_194"
                            geometry={nodes.Object_194.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_194.skeleton}
                          />
                          <skinnedMesh
                            name="Object_196"
                            geometry={nodes.Object_196.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_196.skeleton}
                          />
                          <skinnedMesh
                            name="Object_198"
                            geometry={nodes.Object_198.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_198.skeleton}
                          />
                          <skinnedMesh
                            name="Object_200"
                            geometry={nodes.Object_200.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_200.skeleton}
                          />
                          <skinnedMesh
                            name="Object_202"
                            geometry={nodes.Object_202.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_202.skeleton}
                          />
                          <skinnedMesh
                            name="Object_204"
                            geometry={nodes.Object_204.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_204.skeleton}
                          />
                          <skinnedMesh
                            name="Object_206"
                            geometry={nodes.Object_206.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_206.skeleton}
                          />
                          <skinnedMesh
                            name="Object_208"
                            geometry={nodes.Object_208.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_208.skeleton}
                          />
                          <skinnedMesh
                            name="Object_210"
                            geometry={nodes.Object_210.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_210.skeleton}
                          />
                          <skinnedMesh
                            name="Object_212"
                            geometry={nodes.Object_212.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_212.skeleton}
                          />
                          <skinnedMesh
                            name="Object_214"
                            geometry={nodes.Object_214.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_214.skeleton}
                          />
                          <skinnedMesh
                            name="Object_216"
                            geometry={nodes.Object_216.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_216.skeleton}
                          />
                          <skinnedMesh
                            name="Object_218"
                            geometry={nodes.Object_218.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_218.skeleton}
                          />
                          <skinnedMesh
                            name="Object_220"
                            geometry={nodes.Object_220.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_220.skeleton}
                          />
                          <skinnedMesh
                            name="Object_222"
                            geometry={nodes.Object_222.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_222.skeleton}
                          />
                          <skinnedMesh
                            name="Object_224"
                            geometry={nodes.Object_224.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_224.skeleton}
                          />
                          <skinnedMesh
                            name="Object_226"
                            geometry={nodes.Object_226.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_226.skeleton}
                          />
                          <skinnedMesh
                            name="Object_228"
                            geometry={nodes.Object_228.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_228.skeleton}
                          />
                          <a.group name="Object_161" />
                          <a.group name="Object_163" />
                          <a.group name="Object_165" />
                          <a.group name="Object_167" />
                          <a.group name="Object_169" />
                          <a.group name="Object_171" />
                          <a.group name="Object_173" />
                          <a.group name="Object_175" />
                          <a.group name="Object_177" />
                          <a.group name="Object_179" />
                          <a.group name="Object_181" />
                          <a.group name="Object_183" />
                          <a.group name="Object_185" />
                          <a.group name="Object_187" />
                          <a.group name="Object_189" />
                          <a.group name="Object_191" />
                          <a.group name="Object_193" />
                          <a.group name="Object_195" />
                          <a.group name="Object_197" />
                          <a.group name="Object_199" />
                          <a.group name="Object_201" />
                          <a.group
                            name="Object_203"
                            position={[-13.61232072, -3.32106287, -2.90448232]}
                            scale={1.28994268}
                          />
                          <a.group
                            name="Object_205"
                            position={[0.41226045, -4.25687751, -1.92047406]}
                            scale={1.15518022}
                          />
                          <a.group
                            name="Object_207"
                            position={[-13.482302, -3.21053623, -2.24926673]}
                            scale={1.15489833}
                          />
                          <a.group
                            name="Object_209"
                            position={[-15.99761498, 1.3736911, -1.49772255]}
                          />
                          <a.group
                            name="Object_211"
                            position={[-13.38803308, -0.04739363, -1.51991944]}
                          />
                          <a.group
                            name="Object_213"
                            position={[0, -0.00019343, -1.51991944]}
                          />
                          <a.group
                            name="Object_215"
                            position={[-13.38803291, 1.37413137, -1.25412564]}
                          />
                          <a.group
                            name="Object_217"
                            position={[-13.38803291, -0.04485827, -1.51991944]}
                          />
                          <a.group
                            name="Object_219"
                            position={[13.61232072, -3.32106287, -2.90448232]}
                            scale={[-1.28994268, 1.28994268, 1.28994268]}
                          />
                          <a.group
                            name="Object_221"
                            position={[5.67882576, -4.25687751, -1.92047406]}
                            scale={[1.155, 1.15518022, 1.15518022]}
                          />
                          <a.group
                            name="Object_223"
                            position={[13.482302, -3.21053623, -2.24926673]}
                            scale={[-1.15489833, 1.15489833, 1.15489833]}
                          />
                          <a.group
                            name="Object_225"
                            position={[15.99761498, 1.3736911, -1.49772255]}
                            scale={[-1, 1, 1]}
                          />
                          <a.group name="Object_227" />
                        </a.group>
                      </a.group>
                    </a.group>
                  </a.group>
                </a.group>
              </a.group>
            </a.group>
          </a.group>
        </a.group>
      </a.group>
    </>
  );
};

export default ContactCharacter;
