import React, { useRef, useEffect } from "react";
import { a } from "@react-spring/three";
import { useAnimations, useGLTF } from "@react-three/drei";

import infernapeScene from "../../assets/3d/Infernape.glb";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ijackprovostjr (https://sketchfab.com/ijackprovostjr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-pokedex-3d-pro-infernape-51ec3101d01849d5b0c9930498c9ef47
Title: Pokemon PokeDex 3D Pro Infernape
*/

const Infernape = (props) => {
  const infernApeRef = useRef();
  const { nodes, materials, animations } = useGLTF(infernapeScene);
  const { actions } = useAnimations(animations, infernApeRef);
  console.log(animations);

  useEffect(() => {
    if (actions && actions["ArmatureAction"]) {
      actions["ArmatureAction"].play();
    }
  }, [actions]);

  return (
    <>
      <a.group ref={infernApeRef} {...props} dispose={null}>
        <a.group name="Sketchfab_Scene">
          <a.group
            name="Sketchfab_model"
            rotation={[-Math.PI / 2.2, 0, 2]}
            position={[-60, 129, 60]}
          >
            <a.group name="root" scale={30}>
              <a.group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                <a.group
                  name="Armature_125"
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={1.937}
                >
                  <a.group name="GLTF_created_0">
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <skinnedMesh
                      name="Object_7"
                      geometry={nodes.Object_7.geometry}
                      material={materials.BodyB}
                      skeleton={nodes.Object_7.skeleton}
                    />
                    <skinnedMesh
                      name="Object_9"
                      geometry={nodes.Object_9.geometry}
                      material={materials["Eye.002"]}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <skinnedMesh
                      name="Object_11"
                      geometry={nodes.Object_11.geometry}
                      material={materials.BodyA}
                      skeleton={nodes.Object_11.skeleton}
                    />
                    <skinnedMesh
                      name="Object_13"
                      geometry={nodes.Object_13.geometry}
                      material={materials.BodyA}
                      skeleton={nodes.Object_13.skeleton}
                    />
                    <skinnedMesh
                      name="Object_15"
                      geometry={nodes.Object_15.geometry}
                      material={materials.BodyA}
                      skeleton={nodes.Object_15.skeleton}
                    />
                    <skinnedMesh
                      name="Object_17"
                      geometry={nodes.Object_17.geometry}
                      material={materials.BodyA}
                      skeleton={nodes.Object_17.skeleton}
                    />
                    <skinnedMesh
                      name="Object_19"
                      geometry={nodes.Object_19.geometry}
                      material={materials.BodyA}
                      skeleton={nodes.Object_19.skeleton}
                    />
                    <skinnedMesh
                      name="Object_21"
                      geometry={nodes.Object_21.geometry}
                      material={materials.BodyC_powa}
                      skeleton={nodes.Object_21.skeleton}
                    />
                    <skinnedMesh
                      name="Object_23"
                      geometry={nodes.Object_23.geometry}
                      material={materials.BodyC_line}
                      skeleton={nodes.Object_23.skeleton}
                    />
                    <a.group name="Object_0_116" />
                    <a.group name="Object_1_117" />
                    <a.group name="Object_2_118" />
                    <a.group name="Object_3_119" />
                    <a.group name="Object_4_120" />
                    <a.group name="Object_5_121" />
                    <a.group name="Object_6_122" />
                    <a.group name="Object_7_123" />
                    <a.group name="Object_8_124" />
                  </a.group>
                </a.group>
              </a.group>
            </a.group>
          </a.group>
        </a.group>
      </a.group>
    </>
  );
};

export default Infernape;
