import React, { useRef, useEffect } from "react";
import { a } from "@react-spring/three";
import { useAnimations, useGLTF } from "@react-three/drei";

import scizorScene from "../../assets/3d/scizor.glb";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ijackprovostjr (https://sketchfab.com/ijackprovostjr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-3ds-scizor-cc15c8ab51914206b912ad11e5439274
Title: Pokemon 3DS Scizor
*/

const Scizor = (props) => {
  const scizorRef = useRef();
  const { nodes, materials, animations } = useGLTF(scizorScene);
  const { actions } = useAnimations(animations, scizorRef);

  useEffect(() => {
    if (actions && actions["ArmatureAction.002"]) {
      actions["ArmatureAction.002"].play();
    }
  }, [actions]);

  return (
    <>
      <a.group ref={scizorRef} {...props} dispose={null}>
        <a.group name="Sketchfab_Scene">
          <a.group
            name="Sketchfab_model"
            position={[330, 45, 230]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <a.group name="root" scale={14}>
              <a.group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                <a.group
                  name="Armature_54"
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={3.21}
                >
                  <a.group name="GLTF_created_0">
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <skinnedMesh
                      name="Object_7"
                      geometry={nodes.Object_7.geometry}
                      material={materials["Eye.002"]}
                      skeleton={nodes.Object_7.skeleton}
                    />
                    <skinnedMesh
                      name="Object_9"
                      geometry={nodes.Object_9.geometry}
                      material={materials["Mouth.002"]}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <skinnedMesh
                      name="Object_11"
                      geometry={nodes.Object_11.geometry}
                      material={materials.Wing}
                      skeleton={nodes.Object_11.skeleton}
                    />
                    <skinnedMesh
                      name="Object_13"
                      geometry={nodes.Object_13.geometry}
                      material={materials["Body.001"]}
                      skeleton={nodes.Object_13.skeleton}
                    />
                    <skinnedMesh
                      name="Object_15"
                      geometry={nodes.Object_15.geometry}
                      material={materials["Body.001"]}
                      skeleton={nodes.Object_15.skeleton}
                    />
                    <a.group name="Object_0_49" />
                    <a.group name="Object_1_50" />
                    <a.group name="Object_2_51" />
                    <a.group name="Object_3_52" />
                    <a.group name="Object_4_53" />
                  </a.group>
                </a.group>
              </a.group>
            </a.group>
          </a.group>
        </a.group>
      </a.group>
    </>
  );
};

export default Scizor;
