import React, { useEffect, useRef } from "react";
import { a } from "@react-spring/three";
import { useAnimations, useGLTF } from "@react-three/drei";

import selfScene from "../../assets/3d/self.glb";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: dotflare (https://sketchfab.com/Dotflare)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/truffle-man-e41c6781e4854a1fbe5cdf24a0029aab
Title: Truffle Man
*/

const Self = (props) => {
  const selfRef = useRef();
  const { nodes, materials, animations } = useGLTF(selfScene);

  const { actions } = useAnimations(animations, selfRef);

  useEffect(() => {
    if (actions && actions["Armature|Armature|mixamo.com|Layer0"]) {
      actions["Armature|Armature|mixamo.com|Layer0"].play();
    }
  }, [actions]);

  return (
    <>
      <a.group ref={selfRef} {...props} dispose={null}>
        <a.group name="Sketchfab_Scene">
          <a.group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
            <a.group
              name="d6f42ede6cb54a05919bfed49102f473fbx"
              position={[450, 50, 55]}
              rotation={[Math.PI / 2, 1.3, 0]}
              scale={0.9}
            >
              <a.group name="Object_2">
                <a.group name="RootNode">
                  <a.group
                    name="Light"
                    position={[407.625, 590.386, -100.545]}
                    rotation={[1.89, 0.881, -2.045]}
                    scale={100}
                  >
                    <a.group name="Object_5" rotation={[Math.PI / 2, 0, 0]}>
                      <a.group name="Object_6" />
                    </a.group>
                  </a.group>
                  <a.group
                    name="Camera"
                    position={[735.889, 495.831, 692.579]}
                    rotation={[-Math.PI, 0.756, 2.68]}
                    scale={100}
                  >
                    <a.group name="Object_8" />
                  </a.group>
                  <a.group name="Armature">
                    <a.group name="Object_10">
                      <primitive object={nodes._rootJoint} />
                      <skinnedMesh
                        name="Object_91"
                        geometry={nodes.Object_91.geometry}
                        material={materials["mat0.003"]}
                        skeleton={nodes.Object_91.skeleton}
                      />
                      <skinnedMesh
                        name="Object_93"
                        geometry={nodes.Object_93.geometry}
                        material={materials["mat0.001"]}
                        skeleton={nodes.Object_93.skeleton}
                      />
                      <skinnedMesh
                        name="Object_95"
                        geometry={nodes.Object_95.geometry}
                        material={materials.mat0}
                        skeleton={nodes.Object_95.skeleton}
                      />
                      <skinnedMesh
                        name="Object_97"
                        geometry={nodes.Object_97.geometry}
                        material={materials["mat0.004"]}
                        skeleton={nodes.Object_97.skeleton}
                      />
                      <skinnedMesh
                        name="Object_99"
                        geometry={nodes.Object_99.geometry}
                        material={materials["mat0.002"]}
                        skeleton={nodes.Object_99.skeleton}
                      />
                      <skinnedMesh
                        name="Object_101"
                        geometry={nodes.Object_101.geometry}
                        material={materials["mat0.005"]}
                        skeleton={nodes.Object_101.skeleton}
                      />
                      <a.group
                        name="Object_90"
                        rotation={[-Math.PI / 2, 0, 0]}
                      />
                      <a.group
                        name="Object_92"
                        rotation={[-Math.PI / 2, 0, 0]}
                      />
                      <a.group
                        name="Object_94"
                        rotation={[-Math.PI / 2, 0, 0]}
                      />
                      <a.group
                        name="Object_96"
                        rotation={[-Math.PI / 2, 0, 0]}
                      />
                      <a.group
                        name="Object_98"
                        rotation={[-Math.PI / 2, 0, 0]}
                      />
                      <a.group
                        name="Object_100"
                        rotation={[-Math.PI / 2, 0, 0]}
                      />
                    </a.group>
                  </a.group>
                  <a.group
                    name="Mesh_0074rip"
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <a.group
                    name="Mesh_0085rip"
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <a.group
                    name="Mesh_0082rip"
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <a.group
                    name="Mesh_0072rip"
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <a.group
                    name="Mesh_0088rip"
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <a.group
                    name="Mesh_0073rip"
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                </a.group>
              </a.group>
            </a.group>
          </a.group>
        </a.group>
      </a.group>
    </>
  );
};

export default Self;
