import React, { useRef, useEffect } from "react";
import { a } from "@react-spring/three";
import { useAnimations, useGLTF } from "@react-three/drei";

import umbreonScene from "../../assets/3d/umbreon.glb";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: undecyce (https://sketchfab.com/undecyce)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/umbreon-napping-c7c23cf2a3ab48ac9889f62a79f6234b
Title: Umbreon napping
*/

const Umbreon = (props) => {
  const umbreonRef = useRef();
  const { nodes, materials, animations } = useGLTF(umbreonScene);
  const { actions } = useAnimations(animations, umbreonRef);

  useEffect(() => {
    if (actions && actions["ArmatureAction"]) {
      actions["ArmatureAction"].play();
    }
  }, [actions]);

  return (
    <>
      <a.group ref={umbreonRef} {...props} dispose={null}>
        <a.group name="Sketchfab_Scene">
          <a.group
            name="Sketchfab_model"
            rotation={[-Math.PI / 2, 0, 2]}
            position={[280, 40, -350]}
          >
            <a.group name="root" scale={0.8}>
              <a.group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                <a.group name="pm0197_00_40">
                  <a.group name="GLTF_created_0">
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <skinnedMesh
                      name="Object_7"
                      geometry={nodes.Object_7.geometry}
                      material={materials.m_eyes}
                      skeleton={nodes.Object_7.skeleton}
                    />
                    <skinnedMesh
                      name="Object_9"
                      geometry={nodes.Object_9.geometry}
                      material={materials.m_body}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <skinnedMesh
                      name="Object_11"
                      geometry={nodes.Object_11.geometry}
                      material={materials.m_eyes}
                      skeleton={nodes.Object_11.skeleton}
                    />
                    <skinnedMesh
                      name="Object_13"
                      geometry={nodes.Object_13.geometry}
                      material={materials.m_ring}
                      skeleton={nodes.Object_13.skeleton}
                    />
                    <skinnedMesh
                      name="Object_14"
                      geometry={nodes.Object_14.geometry}
                      material={materials.m_ring}
                      skeleton={nodes.Object_14.skeleton}
                    />
                    <a.group name="Eye_36" />
                    <a.group name="Mesh_0_37" />
                    <a.group name="Mouth_38" />
                    <a.group name="Ring_39" />
                  </a.group>
                </a.group>
              </a.group>
            </a.group>
          </a.group>
        </a.group>
      </a.group>
    </>
  );
};

export default Umbreon;
