import React, { useRef, useEffect } from "react";
import { a } from "@react-spring/three";
import { useAnimations, useGLTF } from "@react-three/drei";

import umbreonScene from "../../assets/3d/umbreon.glb";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ijackprovostjr (https://sketchfab.com/ijackprovostjr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-3ds-celebi-edab2daaf5de4a1bb50c9fc09d667e0b
Title: Pokemon 3DS Celebi
*/

const Umbreon = (props) => {
  const umbreonRef = useRef();
  const { nodes, materials, animations } = useGLTF(umbreonScene);
  const { actions } = useAnimations(animations, umbreonRef);

  useEffect(() => {
    if (actions && actions["ArmatureAction.001"]) {
      actions["ArmatureAction.001"].play();
    }
  }, [actions]);

  return (
    <>
      <a.group ref={umbreonRef} {...props} dispose={null}>
        <a.group name="Sketchfab_Scene">
          <a.group
            name="Sketchfab_model"
            rotation={[-Math.PI / 2, 0, 3]}
            position={[280, 50, -380]}
          >
            <a.group name="root" scale={30}>
              <a.group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                <a.group
                  name="Armature_64"
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={4.417}
                >
                  <a.group name="GLTF_created_0">
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <skinnedMesh
                      name="Object_7"
                      geometry={nodes.Object_7.geometry}
                      material={materials.BodyB}
                      skeleton={nodes.Object_7.skeleton}
                    />
                    <skinnedMesh
                      name="Object_9"
                      geometry={nodes.Object_9.geometry}
                      material={materials["Eye.001"]}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <skinnedMesh
                      name="Object_11"
                      geometry={nodes.Object_11.geometry}
                      material={materials.Mouth}
                      skeleton={nodes.Object_11.skeleton}
                    />
                    <skinnedMesh
                      name="Object_13"
                      geometry={nodes.Object_13.geometry}
                      material={materials.BodyA}
                      skeleton={nodes.Object_13.skeleton}
                    />
                    <skinnedMesh
                      name="Object_15"
                      geometry={nodes.Object_15.geometry}
                      material={materials.BodyA}
                      skeleton={nodes.Object_15.skeleton}
                    />
                    <a.group name="Object_0_59" />
                    <a.group name="Object_1_60" />
                    <a.group name="Object_2_61" />
                    <a.group name="Object_3_62" />
                    <a.group name="Object_4_63" />
                  </a.group>
                </a.group>
              </a.group>
            </a.group>
          </a.group>
        </a.group>
      </a.group>
    </>
  );
};

export default Umbreon;
